version: "3.9"

services:
  app:
    build: .
    container_name: app
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - application_network

  postgres:
    image: postgres:14.5-alpine
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PG_DATA}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - application_network

networks:
  application_network:
    driver: bridge

volumes:
  postgres:
