version: "3.9"

services:
  app:
    build: .
    container_name: app
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  postgres:
    image: postgres:14.5-alpine
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres:
